### ISSUE TITLE
Suggestion: Minimize comments (Icon or "Comment" label) instead of hiding them?

### ISSUE THREAD

**Issue by cansar** [mirnovov/elf#5]
Hi,

I just installed ELF and love it.

I was a bit confused that I had some blank text in some notes only to realize it was metadata comments that were being hidden until clicked into (and only that line?). What do you think about partially hiding them the way you can fold Metadata?

**Comment by cansar** [comment]
For some reason this is what I'm seeing when I toggle Comments on. Default theme.

<img width="121" alt="image" src="https://user-images.githubusercontent.com/92989/150624742-8f32ffd7-bd1c-4a59-9ff8-c5c2b87ac97c.png">

**Comment by cansar** [comment]
When I click on each line I see the underlying line (same as when hidden). 
<img width="112" alt="image" src="https://user-images.githubusercontent.com/92989/150624758-bee549ce-68e0-4ea3-86e5-d0d8e93e47e1.png">

**Comment by mirnovov** [comment]
This should be fixed now; you should only see one `<!>` per line, which is what I intended. There's no fancy click-to-fold stuff yet, but I may add that in the future (probably as an option, since showing stuff by selecting the line is more consistent with other default and ELF Live Preview behaviour).

**Comment by cansar** [comment]
I'm still seeing the same thing, I'm not sure why. I checked that the updates are applied in my `.obsidian/plugins/elf/` folder. I also removed and re-installed the plugin in Elf. My guess is that it's something on my side and I'll try with a different fresh vault as a test but wanted to let you know in case others run into it.

Thanks for all the work!
